apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datadog-notifier
  description: 'A Onboard an Existing Repo to Backstage created via Backstage'
  annotations:
    repo: patterninc/datadog_notifier
  labels:
    CostCenter: DATA
    Environment: stage
    Name: datadog-notifier
    Owner: dev-data-acquisition
    Department: DATA
    CreatedBy: Backstage
spec:
  type: service
  system: data
