name: Publish Datadog Notifier Gem

on:
  push:
    tags:
      - 'v*' # Trigger on version tags, e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build gem
        run: gem build datadog_notifier.gemspec

      - name: Publish gem
        run: gem push *.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
